### ISSUE TITLE
Network multiplayer tech?

### ISSUE THREAD

**Issue by qskousen** [asajs/BallShoot#2]
Been doing a little research and stumbled across this: https://github.com/heroiclabs/nakama/

It has a Godot client. It doesn't have NAT punching, but it does have matchmaking and network relaying which would solve the same problem, and it also has authoritative multiplayer support at up to 30 ticks per second which could be a fun challenge to get implemented after doing the relay style.

It also has built in leaderboards which could be fun.

Thoughts?

**Comment by asajs** [comment]
I thoughts this is a good idea. Don't know how it works though. I'm curious to see it.

**Comment by qskousen** [comment]
I've spun up a Nakama instance, working on integrating.

**Comment by asajs** [comment]
We have decided to use this idea.
